---
title: Sufni
author: Forestry.io
email: info@sufni.eu
description: Sufni egy remekbeszabott
baseurl: "/sufni"
url: https://vestalux.github.io/
defaults:
- scope:
    path: ''
  values:
    layout: default
markdown: kramdown
gems:
- jekyll-feed
- jekyll-menus
